Repository waggle2/wagglewaggle_server, pull requests merged in 2024-03, with the labels that each got.

#111 쪽지기능 유저 정보 반환에 state 추가, 받은 쪽지 신고 기능 추가
  src/domain/blocks/blocks.controller.ts
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.service.ts
  src/domain/reports/dto/report-response.dto.ts
  src/domain/reports/entities/report.entity.ts
  src/domain/reports/reports.controller.ts
  src/domain/reports/reports.service.ts
  src/domain/users/dto/user-profile.dto.ts
Labels: Type: Docs/Chore, Type: Feature

#113 user entity에 blockingUsers 추가, 쪽지기능 차단유저 처리 추가
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.service.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.service.ts
Labels: For: Models/DB, Type: Feature

#114 스티커/코인 관련 처리, 상대 유저 프로필 조회 기능 추가
  src/domain/stickers/stickers.module.ts
  src/domain/stickers/stickers.service.ts
  src/domain/users/dto/other-user-profile.dto.ts
  src/domain/users/entities/user-stickers.entity.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.controller.ts
  src/domain/users/users.module.ts
  src/domain/users/users.service.ts
Labels: Type: Docs/Chore, For: Models/DB, Type: Feature

#116 Fix: 본인인증 버그 해결 #115
  src/domain/users/users.service.ts
Labels: For: API, Type: Errors/Bugs

#118 roles guard 추가, items, reports, blocks에 적용
  src/domain/authentication/decorators/role.decorator.ts
  src/domain/authentication/exceptions/authentication.exception.ts
  src/domain/authentication/guards/roles.guard.ts
  src/domain/blocks/blocks.controller.ts
  src/domain/blocks/blocks.service.ts
  src/domain/items/items.controller.ts
  src/domain/reports/reports.controller.ts
  src/domain/reports/reports.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: Type: Feature

#121 Feature 119 filter block 19
  src/common/utils/getUserIdFromToken.ts
  src/domain/authentication/exceptions/authentication.exception.ts
  src/domain/authentication/guards/adult-authentication.guard.ts
  src/domain/authentication/passport/adult.strategy.ts
  src/domain/blocks/blocks.controller.ts
  src/domain/blocks/blocks.module.ts
  src/domain/blocks/blocks.service.ts
  src/domain/blocks/dto/block-response.dto.ts
  src/domain/blocks/dto/create-block-user.dto.ts
  src/domain/blocks/entities/block.entity.ts
  src/domain/comments/comments.module.ts
  src/domain/messages/messages.service.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: For: Models/DB, Type: Feature, Type: Refactor

#125 Feat: itemType enum 변경 및 마이그레이션 #124
  src/@types/enum/item-type.enum.ts
  src/database/migrations/1710410177498-itemTypeEnumRefactoring.ts
  src/database/migrations/typeOrm.config.ts
  src/domain/items/dto/create-item.dto.ts
Labels: Type: Refactor

#127 투표 기능 수정 및 DTO 추가
  src/domain/pollItems/pollItems.service.ts
  src/domain/polls/dto/poll-response.dto.ts
  src/domain/polls/entities/poll.entity.ts
  src/domain/polls/polls.controller.ts
  src/domain/polls/polls.service.ts
  src/domain/posts/dto/post-response.dto.ts
  src/domain/posts/posts.controller.ts
  src/domain/users/dto/user-profile.dto.ts
Labels: Type: Feature, Type: Refactor

#128 회원가입 시 탈퇴회원과 관련한 버그, 탈퇴회원 재가입 시 처리
  src/@types/enum/user.enum.ts
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.service.ts
  src/domain/authentication/exceptions/authentication.exception.ts
  src/domain/users/dto/update-user.dto.ts
  src/domain/users/users.controller.ts
  src/domain/users/users.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: Type: Errors/Bugs, Type: Feature

#129 전체회원조회 api에 페이지네이션 적용, UserResponseDto 작성 후 적용
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.service.ts
  src/domain/users/dto/user-profile.dto.ts
  src/domain/users/dto/user-response.dto.ts
  src/domain/users/users.controller.ts
  src/domain/users/users.service.ts
Labels: Type: Docs/Chore, For: Models/DB, Type: Refactor

#131 Feat: 투표 수정 API 추가
  src/domain/polls/dto/update-poll.dto.ts
  src/domain/polls/polls.controller.ts
  src/domain/polls/polls.service.ts
Labels: Type: Feature
