Repository waggle2/wagglewaggle_server, pull requests merged in 2024-02, with the labels that each got.

#26 좋아요 도메인 구성, 커스텀 에러 추가, 스웨거 API 응답 추가
  src/app.module.ts
  src/domain/comments/comments.controller.ts
  src/domain/comments/comments.service.ts
  src/domain/comments/dto/response.comments.dto.ts
  src/domain/comments/entities/comment.entity.ts
  src/domain/likes/entities/like.entity.ts
  src/domain/likes/likes.controller.ts
  src/domain/likes/likes.module.ts
  src/domain/likes/likes.service.ts
  src/domain/pollItems/dto/response.pollItem.dto.ts
  src/domain/polls/dto/response.polls.dto.ts
  src/domain/polls/polls.controller.ts
  src/domain/polls/polls.service.ts
  src/domain/posts/dto/create-post.dto.ts
  src/domain/posts/dto/response.posts.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.service.ts
  src/error/http-exception.filter.ts
  src/exceptions/base.exception.interface.ts
  src/exceptions/base.exception.ts
  src/exceptions/domain/comments.exception.ts
  src/exceptions/domain/polls.exception.ts
  src/exceptions/domain/posts.exception.ts
  src/exceptions/exception.enum.ts
  src/exceptions/uncatch.exception.ts
  src/filter/exception.filter.ts
  src/main.ts
Labels: BE

#28 게시글 및 댓글 로직 수정
  src/domain/comments/comments.controller.ts
  src/domain/comments/comments.service.ts
  src/domain/files/files.service.ts
  src/domain/likes/likes.service.ts
  src/domain/polls/polls.service.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/reports/reports.service.ts
  src/domain/sticker/sticker.controller.ts
  src/exceptions/domain/comments.exception.ts
  src/exceptions/domain/posts.exception.ts
  src/exceptions/domain/stickers.exception.ts
  src/exceptions/exception.enum.ts
Labels: BE

#30 Fix: 소셜 로그인, 이메일 로그인, 회원가입 오류 해결 #2
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.module.ts
  src/domain/authentication/authentication.service.ts
  src/domain/authentication/guards/local-authentication.guard.ts
  src/domain/authentication/interfaces/token-payload.interface.ts
  src/domain/authentication/passport/local.strategy.ts
  src/domain/users/dto/create-user.dto.ts
  src/domain/users/entities/exit-reason.entity.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.service.ts
  src/exceptions/domain/authentication.exception.ts
  src/exceptions/domain/users.exception.ts
  src/exceptions/exception.enum.ts
  src/exceptions/uncatch.exception.ts
Labels: BE

#31 게시글 태그와 카테고리 태그 분리, 500에러가 아님에도 500으로 뜨는 버그 픽스
  src/app.module.ts
  src/domain/categories/categories.controller.ts
  src/domain/categories/categories.module.ts
  src/domain/categories/categories.service.ts
  src/domain/categories/entities/category.entity.ts
  src/domain/posts/decorators/posts.decorator.ts
  src/domain/posts/dto/create-post.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.service.ts
  src/domain/types/enum/category.enum.ts
  src/domain/types/enum/tags.enum.ts
  src/exceptions/uncatch.exception.ts
  src/filter/exception.filter.ts
Labels: BE

#37 Refactor: 폴더 구조 변경
  src/@types/decorators/pagination.decorator.ts
  src/@types/enum/animal.enum.ts
  src/@types/enum/category.enum.ts
  src/@types/enum/item-type.enum.ts
  src/@types/enum/report-reason.enum.ts
  src/@types/enum/tags.enum.ts
  src/@types/enum/user.enum.ts
  src/app.module.ts
  src/domain/authentication/authentication.service.ts
  src/domain/authentication/guards/jwt-authentication.guard.ts
  src/domain/authentication/guards/refresh-authentication.guard.ts
  src/domain/comments/comments.controller.ts
  src/domain/comments/comments.service.ts
  src/domain/files/files.controller.ts
  src/domain/files/files.module.ts
  src/domain/health-check/health-check.controller.spec.ts
  src/domain/health-check/health-check.controller.ts
  src/domain/items/dto/create-item.dto.ts
  src/domain/items/entities/item.entity.ts
  src/domain/likes/likes.controller.ts
  src/domain/polls/polls.controller.ts
  src/domain/polls/polls.service.ts
  src/domain/posts/decorators/posts.decorator.ts
  src/domain/posts/dto/create-post.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/presign-urls/presign-urls.controller.ts
  src/domain/reports/dto/create-report.dto.ts
  src/domain/reports/entities/report.entity.ts
  src/domain/search/search.module.ts
  src/domain/search/search.service.ts
  src/domain/sticker/dto/create-sticker.dto.ts
  src/domain/sticker/entities/sticker.entity.ts
  src/domain/sticker/sticker.controller.ts
  src/domain/users/dto/create-user.dto.ts
  src/domain/users/dto/exit-reason.dto.ts
  src/domain/users/entities/credential.entity.ts
  src/domain/users/entities/exit-reason.entity.ts
  src/domain/users/entities/user-authority.entity.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.service.ts
  src/lib/config/mailer.config.ts
  src/lib/config/multer-options.factory.ts
  src/lib/config/s3.config.ts
  src/lib/config/typeorm.config.ts
  src/lib/exceptions/base.exception.interface.ts
  src/lib/exceptions/base.exception.ts
  src/lib/exceptions/domain/authentication.exception.ts
  src/lib/exceptions/domain/comments.exception.ts
  src/lib/exceptions/domain/polls.exception.ts
  src/lib/exceptions/domain/posts.exception.ts
  src/lib/exceptions/domain/stickers.exception.ts
  src/lib/exceptions/domain/users.exception.ts
  src/lib/exceptions/exception.enum.ts
  src/lib/exceptions/uncatch.exception.ts
  src/lib/filter/exception.filter.ts
  src/lib/templates/email-verification.hbs
  src/main.ts
Labels: BE

#39 Fix: user 관련 기능 오류 수정, .hbs파일 임시 작성 #2
  nest-cli.json
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.service.ts
  src/domain/users/users.controller.ts
  src/domain/users/users.service.ts
  src/lib/config/mailer.config.ts
  src/lib/exceptions/domain/users.exception.ts
  src/lib/exceptions/exception.enum.ts
  src/lib/templates/email-verification.hbs
  src/lib/templates/password-reset.hbs
  src/lib/templates/sign-up.hbs
Labels: BE

#42 기존 도메인에 유저 연결
  src/app.module.ts
  src/domain/comments/comments.controller.ts
  src/domain/comments/comments.service.ts
  src/domain/comments/entities/comment.entity.ts
  src/domain/comments/exceptions/comments.exception.ts
  src/domain/likes/entities/like.entity.ts
  src/domain/likes/likes.controller.ts
  src/domain/likes/likes.module.ts
  src/domain/likes/likes.service.ts
  src/domain/pollItems/entities/pollItem.entity.ts
  src/domain/pollItems/pollItems.service.ts
  src/domain/polls/entities/poll.entity.ts
  src/domain/polls/exceptions/polls.exception.ts
  src/domain/polls/polls.controller.ts
  src/domain/polls/polls.service.ts
  src/domain/posts/dto/create-post.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/exceptions/likes.exception.ts
  src/domain/posts/exceptions/posts.exception.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/reports/entities/report.entity.ts
  src/domain/reports/reports.controller.ts
  src/domain/reports/reports.service.ts
  src/domain/sticker/sticker.module.ts
  src/domain/sticker/sticker.service.ts
  src/domain/stickers/dto/create-sticker.dto.ts
  src/domain/stickers/dto/update-sticker.dto.ts
  src/domain/stickers/entities/sticker.entity.ts
  src/domain/stickers/exceptions/stickers.exception.ts
  src/domain/stickers/stickers.controller.ts
  src/domain/stickers/stickers.module.ts
  src/domain/stickers/stickers.service.ts
  src/domain/users/entities/user.entity.ts
  src/lib/exceptions/domain/authentication.exception.ts
  src/lib/exceptions/exception.enum.ts
  src/lib/filter/exception.filter.ts
Labels: BE

#43 Feat: Item 관련 구체적으로 필요한 기능들 추가(포인트샵, 관리자 페이지) #11
  src/domain/authentication/authentication.controller.ts
  src/domain/items/dto/create-item.dto.ts
  src/domain/items/entities/item-cart.entity.ts
  src/domain/items/entities/item.entity.ts
  src/domain/items/items.controller.ts
  src/domain/items/items.module.ts
  src/domain/items/items.service.ts
  src/domain/users/entities/exit-reason.entity.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.module.ts
  src/domain/users/users.service.ts
  src/lib/exceptions/domain/items.exception.ts
  src/lib/exceptions/exception.enum.ts
Labels: BE

#45 Fix: 동물별 카트, 포인트에 따른 기능 수정 #11
  src/domain/items/entities/item-cart.entity.ts
  src/domain/items/items.controller.ts
  src/domain/items/items.service.ts
  src/domain/users/entities/profile-items.entity.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.module.ts
  src/domain/users/users.service.ts
Labels: BE

#46 Docs: user, authentication 스웨거 문서 추가 #2
  src/@types/http-response.ts
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.service.ts
  src/domain/users/dto/create-user.dto.ts
  src/domain/users/users.controller.ts
Labels: documentation

#47 Docs: item 스웨거 추가 #11
  src/domain/items/items.controller.ts
Labels: documentation

#48 Fix: 쿠키 만료시간 설정
  src/domain/authentication/authentication.service.ts
Labels: BE

#49 Feat: 유저 마이페이지 보유 아이템 조회, 착용 아이템 조회, 아이템 착용 기능 추가 #11
  src/domain/authentication/authentication.service.ts
  src/domain/items/interfaces/item-with-ownership.interface.ts
  src/domain/items/items.controller.ts
  src/domain/items/items.module.ts
  src/domain/items/items.service.ts
Labels: BE

#50 Fix: 액세스 토큰 발급 요청 메서드 수정
  src/domain/authentication/authentication.controller.ts
Labels: BE

#52 Fix: 쿠키 설정 변경
  src/domain/authentication/authentication.service.ts
Labels: BE

#53 Fix: 아이템 장바구니 추가 수정
  src/domain/items/items.controller.ts
Labels: BE

#54 Fix: 회원가입 에러처리
  src/domain/authentication/authentication.service.ts
Labels: BE

#56 Fix: 쿠키 samsite, secure 설정
  src/domain/authentication/authentication.service.ts
Labels: BE

#58 Fix: 쿠키 설정 일시적으로 변경
  src/domain/authentication/authentication.service.ts
Labels: BE

#59 Refactor: point 명칭을 coin으로 수정
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.service.ts
  src/domain/items/entities/item-cart.entity.ts
  src/domain/items/items.controller.ts
  src/domain/items/items.service.ts
  src/domain/users/entities/user.entity.ts
Labels: BE

#60 게시글, 투표 수정
  package-lock.json
  package.json
  src/common/dto/SuccessCommonResponse.dto.ts
  src/common/dto/page/page-option.dto.ts
  src/domain/pollItems/pollItems.service.ts
  src/domain/polls/dto/create-poll.dto.ts
  src/domain/polls/dto/update-poll.dto.ts
  src/domain/polls/entities/poll.entity.ts
  src/domain/polls/polls.service.ts
  src/domain/posts/decorators/posts.decorator.ts
  src/domain/posts/dto/post-find.dto.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.service.ts
  src/domain/search/search.service.ts
  src/main.ts
Labels: BE

#61 Feat: 코인 추가 기능 임시 추가
  src/domain/authentication/authentication.controller.ts
  src/domain/authentication/authentication.service.ts
  src/domain/users/users.controller.ts
  src/domain/users/users.service.ts
Labels: BE

#62 Fix: ES 에러, 해결될 때까지 like 쿼리로 대체 및 게시글 모델 수정
  docker-compose.dev.yml
  docker-compose.prod.yml
  scripts/deploy-dev.sh
  scripts/deploy.sh
  src/app.module.ts
  src/common/dto/page/page-options.dto.ts
  src/domain/posts/dto/create-post.dto.ts
  src/domain/posts/dto/post-find.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/search/search.module.ts
  src/domain/search/search.service.ts
Labels: bug, BE

#63 Fix: 전체 게시글 조회에 작성자 정보 추가
  src/common/dto/page/page-options.dto.ts
  src/domain/posts/posts.service.ts
Labels: BE

#64 Feat: 게시글 조회 dto 추가
  src/common/dto/page/page-options.dto.ts
  src/domain/posts/dto/post-entry-response.dto.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.repository.ts
  src/domain/posts/posts.service.ts
Labels: BE

#65 Feat: Message, MessageRoom entity 추가, 메세지 기능 관련 파일 추가 #55
  src/app.module.ts
  src/domain/messages/dto/create-message.dto.ts
  src/domain/messages/dto/update-message.dto.ts
  src/domain/messages/entities/message-room.entity.ts
  src/domain/messages/entities/message.entity.ts
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.module.ts
  src/domain/messages/messages.service.ts
  src/domain/users/entities/user.entity.ts
Labels: BE

#66 Fix: 소셜로그인 부분 수정
  src/domain/authentication/authentication.controller.ts
Labels: BE

#67 Enum 형식 변경에 의한 마이그레이션 및 API 응답 수정
  package-lock.json
  package.json
  src/@types/enum/animal.enum.ts
  src/@types/enum/tags.enum.ts
  src/app.module.ts
  src/common/decorators/success-response.decorator.ts
  src/common/dto/SuccessCommonResponse.dto.ts
  src/common/dto/page/page-meta-dto.interface.ts
  src/common/dto/page/page-meta.dto.ts
  src/common/dto/page/page.dto.ts
  src/common/utils/enumNumberToArray.ts
  src/common/utils/makeInstnaceByApiProperty.ts
  src/common/utils/mergeTwoObj.ts
  src/database/DatabaseOption.interface.ts
  src/database/database.module.ts
  src/database/migrations/1708161878890-AnimalEnumRefactoring.ts
  src/database/migrations/typeOrm.config.ts
  src/domain/comments/dto/comment-response.dto.ts
  src/domain/polls/dto/poll-response.dto.ts
  src/domain/posts/dto/post-entry-response.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/presign-urls/dto/presign-urls.dto.ts
  src/domain/presign-urls/presign-urls.controller.ts
  src/domain/users/dto/user-response.dto.ts
  src/domain/users/entities/user.entity.ts
  src/lib/config/typeorm.config.ts
Labels: BE

#69 Fix: post API 응답 수정
  src/app.module.ts
  src/domain/comments/comments.controller.ts
  src/domain/comments/comments.service.ts
  src/domain/comments/dto/comment-find.dto.ts
  src/domain/comments/dto/comment-response.dto.ts
  src/domain/messages/messages.controller.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/users/dto/user-profile.dto.ts
Labels: BE

#72 제네릭 성공 데코레이션 생성, 각종 도메인 dto 추가, 스웨거 수정
  src/common/decorators/pagination-success-response.decorator.ts
  src/common/decorators/success-response.decorator.ts
  src/common/dto/SuccessCommonResponse.dto.ts
  src/common/dto/page/page-meta-dto.interface.ts
  src/domain/comments/comments.controller.ts
  src/domain/pollItems/entities/pollItem.entity.ts
  src/domain/pollItems/pollItems.module.ts
  src/domain/pollItems/pollItems.service.ts
  src/domain/polls/dto/poll-response.dto.ts
  src/domain/polls/entities/poll.entity.ts
  src/domain/polls/exceptions/polls.exception.ts
  src/domain/polls/polls.controller.ts
  src/domain/polls/polls.module.ts
  src/domain/posts/dto/post-entry-response.dto.ts
  src/domain/posts/dto/post-response.dto.ts
  src/domain/posts/posts.controller.ts
  src/domain/reports/dto/report-response.dto.ts
  src/domain/reports/reports.controller.ts
  src/domain/reports/reports.service.ts
  src/domain/stickers/dto/sticker-response.dto.ts
  src/domain/stickers/stickers.controller.ts
  src/lib/exceptions/exception.enum.ts
  src/main.ts
Labels: For: Utils, Type: Feature, Type: Refactor

#74 검색 기록 기능 추가
  src/app.module.ts
  src/domain/comments/dto/comment-response.dto.ts
  src/domain/posts/dto/post-entry-response.dto.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/search-histories/dto/create-search-history.dto.ts
  src/domain/search-histories/entities/search-history.entity.ts
  src/domain/search-histories/exceptions/search-histories.exception.ts
  src/domain/search-histories/search-histories.controller.ts
  src/domain/search-histories/search-histories.module.ts
  src/domain/search-histories/search-histories.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: For: Models/DB, Type: Errors/Bugs, Type: Feature

#76 Fix: 토큰 에러 버그 픽스 및 검색 기록 API 수정
  src/domain/posts/posts.controller.ts
  src/domain/search-histories/entities/search-history.entity.ts
  src/domain/search-histories/search-histories.controller.ts
Labels: Type: Docs/Chore, Type: Errors/Bugs

#77 Feat: 건의사항 기능 추가
  src/app.module.ts
  src/domain/feedbacks/dto/create-feedback.dto.ts
  src/domain/feedbacks/entities/feedback.entity.ts
  src/domain/feedbacks/exceptions/feedbacks.exception.ts
  src/domain/feedbacks/feedbacks.controller.ts
  src/domain/feedbacks/feedbacks.module.ts
  src/domain/feedbacks/feedbacks.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: For: Models/DB, Type: Feature

#81 단일 게시글 조회 API에서 닉네임 없는 버그 픽스
  src/domain/posts/posts.service.ts
Labels: Type: Errors/Bugs

#84 Column 데코레이터 string 타입 및 길이 지정
  src/domain/comments/entities/comment.entity.ts
  src/domain/feedbacks/dto/create-feedback.dto.ts
  src/domain/feedbacks/entities/feedback.entity.ts
  src/domain/pollItems/dto/create-pollItem.dto.ts
  src/domain/pollItems/dto/update-pollItem.dto.ts
  src/domain/pollItems/entities/pollItem.entity.ts
  src/domain/polls/dto/create-poll.dto.ts
  src/domain/polls/dto/update-poll.dto.ts
  src/domain/polls/entities/poll.entity.ts
  src/domain/posts/entities/post.entity.ts
  src/domain/reports/dto/create-report.dto.ts
  src/domain/reports/entities/report.entity.ts
Labels: For: Models/DB, Type: Errors/Bugs

#86 피드백 API 연동, 사용자 피드백 받기
  package-lock.json
  package.json
  src/domain/feedbacks/feedbacks.module.ts
  src/domain/feedbacks/feedbacks.service.ts
Labels: For: API, Type: Feature

#89 Fix: message 관련 기능 자세히 작성
  src/domain/authentication/authentication.service.ts
  src/domain/authentication/exceptions/authentication.exception.ts
  src/domain/authentication/guards/jwt-authentication.guard.ts
  src/domain/authentication/guards/refresh-authentication.guard.ts
  src/domain/feedbacks/feedbacks.controller.ts
  src/domain/items/exceptions/items.exception.ts
  src/domain/items/items.controller.ts
  src/domain/items/items.service.ts
  src/domain/messages/dto/message-response.dto.ts
  src/domain/messages/entities/message-room.entity.ts
  src/domain/messages/entities/message.entity.ts
  src/domain/messages/exceptions/message.exception.ts
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.module.ts
  src/domain/messages/messages.service.ts
  src/domain/posts/posts.controller.ts
  src/domain/reports/reports.service.ts
  src/domain/users/dto/user-profile.dto.ts
  src/domain/users/exceptions/users.exception.ts
  src/domain/users/users.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: Type: Feature, Type: Refactor

#91 Docs: message 기능 스웨거 추가 #55
  src/domain/messages/dto/create-message.dto.ts
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.service.ts
  src/domain/users/dto/create-user.dto.ts
Labels: Type: Docs/Chore

#93 Fix: 로그아웃, 아이템 장바구니 추가 api 요청메서드 수정
  src/domain/authentication/authentication.controller.ts
  src/domain/items/items.controller.ts
Labels: Type: Errors/Bugs

#94 게시글 아이템 조인 로직 추가, 레디스 config 분리, 환경별로 다르게 실행
  docker-compose.local.yml
  src/app.module.ts
  src/common/utils/applyPaging.ts
  src/domain/posts/dto/post-entry-response.dto.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.service.ts
  src/domain/redis-cache/redis-cache.module.ts
Labels: For: Models/DB, Type: Feature

#95 Fix: 비회원 게시글 조회 되도록
  src/domain/posts/posts.controller.ts
Labels: Type: Errors/Bugs

#97 messageRoom 쿼리빌더 리팩토링, getRooms lastMessage에 createdAt 추가
  src/domain/messages/dto/message-response.dto.ts
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.service.ts
Labels: Type: Feature, Type: Refactor

#100 Feat: messageRoom 신고 기능 추가 #55
  src/domain/messages/entities/message.entity.ts
  src/domain/messages/messages.module.ts
  src/domain/reports/dto/report-response.dto.ts
  src/domain/reports/entities/report.entity.ts
  src/domain/reports/reports.controller.ts
  src/domain/reports/reports.module.ts
  src/domain/reports/reports.service.ts
Labels: Type: Feature

#101 배포 스크립트 변경 및 엘라스틱서치 사용 로직 추가
  .dockerignore
  .gitignore
  docker-compose.dev.yml
  docker-compose.local.yml
  docker-compose.prod.yml
  mapping.json
  scripts/deploy-dev.sh
  scripts/deploy.sh
  src/app.module.ts
  src/domain/comments/comments.controller.ts
  src/domain/comments/comments.module.ts
  src/domain/comments/comments.service.ts
  src/domain/posts/posts.controller.ts
  src/domain/posts/posts.module.ts
  src/domain/posts/posts.service.ts
  src/domain/search/search.module.ts
  src/domain/search/search.service.ts
Labels: Type: Docs/Chore, For: API, For: Deploy, Type: Feature

#102 Feature 96 docker
  scripts/deploy-dev.sh
  scripts/deploy.sh
Labels: Type: Docs/Chore, For: Deploy

#104 Fix: 스티커 수정 및 댓글 페이지네이션 버그 수정
  src/domain/comments/comments.service.ts
  src/domain/stickers/stickers.service.ts
Labels: Type: Errors/Bugs

#105 Feat: 차단기능 추가 #99
  src/app.module.ts
  src/domain/authentication/exceptions/authentication.exception.ts
  src/domain/blocks/blocks.controller.ts
  src/domain/blocks/blocks.module.ts
  src/domain/blocks/blocks.service.ts
  src/domain/blocks/dto/block-response.dto.ts
  src/domain/blocks/dto/create-block-user.dto.ts
  src/domain/blocks/entities/block.entity.ts
  src/domain/blocks/exceptions/block.exception.ts
  src/domain/users/entities/user.entity.ts
  src/domain/users/users.service.ts
  src/lib/exceptions/exception.enum.ts
Labels: Type: Docs/Chore, For: Models/DB, Type: Feature

#107 Fix: message 기능 버그 수정 #106
  src/domain/messages/dto/message-response.dto.ts
  src/domain/messages/entities/message.entity.ts
  src/domain/messages/messages.controller.ts
  src/domain/messages/messages.service.ts
Labels: Type: Errors/Bugs
